# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 13:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import tracks.models.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='manual', max_length=50)),
                ('provider_id', models.CharField(blank=True, max_length=50, null=True)),
                ('simple', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=tracks.models.base.build_image_path)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to=tracks.models.base.build_thumb_path)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='track', to='sport.SportSession')),
            ],
        ),
        migrations.CreateModel(
            name='TrackFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='details', max_length=50)),
                ('md5', models.CharField(max_length=32)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tracks.Track')),
            ],
        ),
        migrations.CreateModel(
            name='TrackSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('distance', models.FloatField(default=0)),
                ('time', models.FloatField(default=0)),
                ('speed', models.FloatField(default=0)),
                ('speed_max', models.FloatField(default=0)),
                ('elevation_min', models.FloatField(default=0)),
                ('elevation_max', models.FloatField(default=0)),
                ('elevation_gain', models.FloatField(default=0)),
                ('elevation_loss', models.FloatField(default=0)),
                ('energy', models.FloatField(default=0)),
                ('distance_total', models.FloatField(default=0)),
                ('time_total', models.FloatField(default=0)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('position_start', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('position_end', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='tracks.Track')),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='split_total',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_track', to='tracks.TrackSplit'),
        ),
        migrations.AlterUniqueTogether(
            name='tracksplit',
            unique_together=set([('track', 'position')]),
        ),
        migrations.AlterUniqueTogether(
            name='trackfile',
            unique_together=set([('track', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([('provider', 'provider_id')]),
        ),
    ]
