# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_athletes', models.IntegerField(default=0)),
                ('nb_trainers', models.IntegerField(default=0)),
                ('nb_staff', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid', 'Paid'), ('expired', 'Expired'), ('error', 'Error')], default='active', max_length=20)),
                ('mangopay_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('level', models.CharField(choices=[('free', 'Free'), ('premium_s', 'Premium Small - 9,90€'), ('premium_m', 'Premium Medium - 19,90€'), ('premium_l', 'Premium Large - 49,90€')], default='free', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='club.Club')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('FAILED', 'Failed'), ('SUCCEEDED', 'Succeeded')], default='CREATED', max_length=20)),
                ('mangopay_id', models.CharField(max_length=50, unique=True)),
                ('response', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='club.Club')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.PaymentPeriod')),
            ],
        ),
    ]
