# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('sport', '0001_initial'),
        ('plan', '0001_initial'),
        ('messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansessionapplied',
            name='sport_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_session', to='sport.SportSession'),
        ),
        migrations.AddField(
            model_name='plansession',
            name='comments',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_session', to='messages.Conversation'),
        ),
        migrations.AddField(
            model_name='plansession',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_sessions', to='events.Place'),
        ),
        migrations.AddField(
            model_name='plansession',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='plan.Plan'),
        ),
        migrations.AddField(
            model_name='plansession',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.Sport'),
        ),
        migrations.AddField(
            model_name='planapplied',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='plan.Plan'),
        ),
    ]
