# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Club name')),
                ('slug', models.SlugField(help_text="Represents the club's name in urls", max_length=20, unique=True, verbose_name='Slug')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('zipcode', models.CharField(max_length=10, verbose_name='Zip code')),
                ('city', models.CharField(max_length=250, verbose_name='City')),
                ('country', django_countries.fields.CountryField(default='FR', max_length=2, verbose_name='Country')),
                ('mangopay_id', models.CharField(blank=True, max_length=50, null=True)),
                ('wallet_id', models.CharField(blank=True, max_length=50, null=True)),
                ('card_id', models.CharField(blank=True, max_length=50, null=True)),
                ('demo', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False, help_text='When private, a club is only accessible y its members', verbose_name='Private club')),
                ('mailing_list', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Group name')),
                ('slug', models.SlugField(verbose_name='Name in the url')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('mailing_list', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(choices=[('create', 'Create a club (Beta)'), ('join', 'Join a club')], max_length=15)),
                ('slug', models.CharField(blank=True, max_length=30, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('used', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Link name')),
                ('url', models.URLField(max_length=250, verbose_name='Link address')),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('athlete', 'Athlete'), ('trainer', 'Trainer'), ('staff', 'Staff'), ('archive', 'Archive'), ('prospect', 'Prospect'), ('delete', 'Delete')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club')),
            ],
        ),
    ]
