# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 13:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembership',
            name='trainers',
            field=models.ManyToManyField(related_name='trainees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clublink',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='club.Club'),
        ),
        migrations.AddField(
            model_name='clubinvite',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='club.Club'),
        ),
        migrations.AddField(
            model_name='clubinvite',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubinvite',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubgroup',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='club.Club'),
        ),
        migrations.AddField(
            model_name='clubgroup',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubgroup',
            name='members',
            field=models.ManyToManyField(related_name='groups', to='club.ClubMembership'),
        ),
        migrations.AddField(
            model_name='club',
            name='main_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_main_trainer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(through='club.ClubMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='clubmembership',
            unique_together=set([('user', 'club')]),
        ),
        migrations.AlterUniqueTogether(
            name='clubinvite',
            unique_together=set([('recipient', 'type')]),
        ),
        migrations.AlterUniqueTogether(
            name='clubgroup',
            unique_together=set([('club', 'slug')]),
        ),
    ]
