# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('distance', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sport_race_category',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('depth', models.IntegerField(default=0)),
                ('strava_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'sport_list',
            },
        ),
        migrations.CreateModel(
            name='SportDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'sport_day',
            },
        ),
        migrations.CreateModel(
            name='SportSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='session comment')),
                ('comment_html', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('training', 'Training'), ('race', 'Race'), ('rest', 'Rest')], default='training', max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('note', models.IntegerField(blank=True, null=True)),
                ('time', models.DurationField(blank=True, null=True, verbose_name='Time')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distance')),
                ('elevation_gain', models.FloatField(blank=True, null=True, verbose_name='Elevation gain')),
                ('elevation_loss', models.FloatField(blank=True, null=True, verbose_name='Elevation loss')),
                ('gcal_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sport_session',
            },
        ),
        migrations.CreateModel(
            name='SportWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2013)),
                ('week', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('task', models.CharField(blank=True, max_length=36, null=True)),
                ('conversation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week', to='messages.Conversation')),
            ],
            options={
                'db_table': 'sport_week',
            },
        ),
    ]
