# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sport', '0001_initial'),
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearitem',
            name='sports',
            field=models.ManyToManyField(blank=True, to='sport.Sport', verbose_name='Default sports'),
        ),
    ]
