# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 13:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('badges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badge',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='badges.BadgeCategory'),
        ),
        migrations.AddField(
            model_name='badge',
            name='users',
            field=models.ManyToManyField(related_name='badges', through='badges.BadgeUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='badgeuser',
            unique_together=set([('badge', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together=set([('category', 'position')]),
        ),
    ]
